name: sp_web
description: SmartPlaylist web editor frontend
publish_to: none
resolution: workspace

environment:
  sdk: ^3.10.0
  flutter: '>=3.38.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod:
  go_router:
  http:
  sp_shared:
    path: ../sp_shared
  web: ^1.1.1
