name: sp_server
description: SmartPlaylist web editor backend
publish_to: none
resolution: workspace

environment:
  sdk: ^3.10.0

dependencies:
  http: ^1.3.0
  sp_shared:
    path: ../sp_shared
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  shelf_static: ^1.1.0

dev_dependencies:
  test: ^1.25.0
