name: sp_server
description: SmartPlaylist web editor backend
publish_to: none
resolution: workspace

environment:
  sdk: ^3.10.0

dependencies:
  crypto: ^3.0.0
  http: ^1.3.0
  sp_shared:
    path: ../sp_shared
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  xml: ^6.5.0

dev_dependencies:
  test: ^1.25.0
